-- Query No: 3
CALL "CELONIS".DROP_IF_EXISTS ('CELONIS','O2C_VBAP');
-- Query No: 4
CREATE VIEW "CELONIS"."O2C_VBAP" AS
SELECT DISTINCT
    VBAP.MANDT,
    VBAP.VBELN,
    VBAP.POSNR,
    VBAP.MATNR,
    VBAP.MATWA,
    VBAP.PMATN,
    VBAP.CHARG,
    VBAP.MATKL,
    CASE WHEN COALESCE(TRIM(VBAP."ABGRU"), '') = '' THEN NULL ELSE VBAP."ABGRU" END AS "ABGRU",
    VBAP.ZWERT,
    VBAP.ZMENG,
    VBAP.MEINS,
    VBAP.POSEX,
    VBAP.VKGRU,
    VBAP.FMENG,
    VBAP.SPART,
    VBAP.GSBER,
    VBAP.NETWR,
    VBAP.WAERK,
    VBAP.ANTLF,
    VBAP.KZTLF,
    VBAP.CHSPL,
    VBAP.KWMENG,
    VBAP.LSMENG,
    VBAP.KBMENG,
    VBAP.KLMENG,
    VBAP.VRKME,
    VBAP.UMVKZ,
    VBAP.UMVKN,
    VBAP.BRGEW,
    VBAP.NTGEW,
    VBAP.GEWEI,
    VBAP.VOLUM,
    VBAP.VOLEH,
    VBAP.VBELV,
    VBAP.POSNV,
    VBAP.VGBEL,
    VBAP.VGPOS,
    VBAP.VOREF,
    VBAP.UPFLU,
    VBAP.ERLRE,
    VBAP.LPRIO,
    VBAP.WERKS,
    VBAP.LGORT,
    CAST(VBAP."STDAT" AS DATE) AS "STDAT",
    CAST(VBAP."ERDAT" AS DATE) AS "ERDAT",
    CAST(VBAP."ERZET" AS TIME) AS "ERZET",
    VBAP.NETPR,
    VBAP.KPEIN,
    VBAP.KMEIN,
    VBAP.SHKZG,
    VBAP.LFMNG,
    CAST(VBAP."AEDAT" AS DATE) AS "AEDAT",
    VBAP.PS_PSP_PNR,
    VBAP.AUFNR,
    VBAP.OBJNR,
    VBAP.VGTYP,
    VBAP.CONTNBR,
    VBAP.CONTITM,
    VBAP.AUDAT,
    VBAP.STATUS,
    VBAP.LABSG,
  	CAST(VBAP."ABDAT" AS DATE) AS "TS_ABDAT",
  	CAST(VBAP."AEDAT" AS DATE) AS "TS_AEDAT",
  	CAST(VBAP."ERDAT" AS DATE) AS "TS_ERDAT",
  	CAST(VBAP."STADAT" AS DATE) AS "TS_STADAT",
  	CAST(VBAP."STDAT" AS DATE) AS "TS_STDAT",
  	CAST(VBAP."ERZET" AS TIME) AS "TS_ERZET",
	COALESCE(VBPA_WE."KUNNR",VBPA_WE2."KUNNR") AS "VBPA_WE",
	MAKT."MAKTX" AS "MATNR_TEXT",
	COALESCE(T023T."WGBEZ",'') AS "MATKL_TEXT",
	T001W."NAME1" AS "WERKS_TEXT",
    T001W."NAME2" AS "WERKS_TEXT2",
	T001L."LGOBE" AS "LGORT_TEXT",
	TVSTT."VTEXT" AS "VSTEL_TEXT",
	TVKMT."VTEXT" AS "KTGRM_TEXT",
	TVAPT."VTEXT" AS "PSTYV_TEXT",
	TVAGT."BEZEI" AS "ABGRU_TEXT",
    -- BEGIN Custom Rehau
    CASE
        WHEN LEFT(VBAP.PRCTR, 1) = 'C' THEN 'VG'
        WHEN LEFT(VBAP.PRCTR, 1) = 'I' AND VBAK.VKORG <> LOCATIONS.BUKRS THEN 'GI'
        WHEN LEFT(VBAP.PRCTR, 1) = 'I' AND VBAK.VKORG = LOCATIONS.BUKRS THEN 'HG'
        WHEN LEFT(VBAP.PRCTR, 1) NOT IN ('I','C') THEN 'GI'
    END AS "TYPE_OF_TRANSACTION",
    MKT_AREA."MARKET_AREA" AS "MARKET_AREA",
    -- END Custom Rehau
	C."NETWR_CONVERTED" AS "NETWR_CONVERTED",
	C."NETPR_CONVERTED" AS "NETPR_CONVERTED",
    C."_CASE_KEY" AS "_CASE_KEY"
    --COALESCE(VBKD_1.BSTDK, VBKD_2.BSTDK, '') AS "VBKD_BSTDK"
FROM
  "CELONIS"."_CEL_O2C_CASES_VIEW" AS C
  JOIN "LAKE"."VBAP" AS VBAP ON 1=1
    	AND VBAP."MANDT" = C."MANDT"
    	AND VBAP."VBELN" = C."VBELN"
    	AND VBAP."POSNR" = C."POSNR"
    -- Fetching WE from Partnertable
    LEFT JOIN "LAKE"."VBPA" AS VBPA_WE ON 1=1
	    AND VBPA_WE."MANDT" = VBAP."MANDT"
	    AND VBPA_WE."VBELN" = VBAP."VBELN"
	    AND VBPA_WE."POSNR" = VBAP."POSNR"
	    and VBPA_WE."PARVW" = 'WE'
    LEFT JOIN "LAKE"."VBPA" AS VBPA_WE2 ON 1=1
	    AND VBPA_WE2."MANDT" = VBAP."MANDT"
	    AND VBPA_WE2."VBELN" = VBAP."VBELN"
	    AND COALESCE (TRIM(LEADING '0' FROM VBPA_WE2."POSNR"),'') = ''
	    and VBPA_WE2."PARVW" = 'WE'
    /*LEFT JOIN LAKE.VBKD AS VBKD_1 ON 1=1
        AND VBKD_1.MANDT = VBAP.MANDT
        AND VBKD_1.VBELN = VBAP.VBELN
        AND VBKD_1.POSNR = VBAP.POSNR
        AND VBKD_1.POSNR <> '000000'
    LEFT JOIN LAKE.VBKD AS VBKD_2 ON 1=1
        AND VBKD_2.MANDT = VBAP.MANDT
        AND VBKD_2.VBELN = VBAP.VBELN
        AND VBKD_2.POSNR = '000000'*/
	-- Rehau Customization for "Geschäftsart"
    LEFT JOIN LAKE."VBAK" AS VBAK ON 1=1
        AND VBAK."MANDT" = VBAP."MANDT"
        AND VBAK."VBELN" = VBAP."VBELN"
    LEFT JOIN LAKE."ZRH_CA_LOCATIONS" AS LOCATIONS ON 1=1
    	AND VBAK."MANDT" = LOCATIONS."MANDT"
    	AND VBAK."VKBUR" = LOCATIONS."LOCATION"
    -- End of Rehau Customization
        -- BEGIN Custom Rehau
    LEFT JOIN "LAKE"."ZRH_BI_MKT_AREA" AS MKT_AREA ON 1=1
        -- possibly necessary to restrict on P1A
        AND C."PG" = MKT_AREA.IND
        AND CAST(VBAK."ERDAT" AS DATE) <= CAST(MKT_AREA."DATBI" AS DATE)
        AND CAST(VBAK."ERDAT" AS DATE) >= CAST(MKT_AREA."DATAB" AS DATE)
        AND VBAK."VKBUR" = MKT_AREA."SALESOFF"
    -- END CUSTOM REHAU
	LEFT JOIN "LAKE"."MAKT" ON 1=1
    	AND VBAP."MANDT" = MAKT."MANDT"
		AND VBAP."MATNR" = MAKT."MATNR"
		AND MAKT."SPRAS" = 'E'
		--AND MAKT."SPRAS" = '{{SPRAS}}'
	LEFT JOIN "LAKE"."T001W" ON 1=1
		AND VBAP."MANDT" = T001W."MANDT"
		AND VBAP."WERKS" = T001W."WERKS"
	LEFT JOIN "LAKE"."T001L" ON 1=1
		AND VBAP."MANDT" = T001L."MANDT"
		AND VBAP."WERKS" = T001L."WERKS"
		AND VBAP."LGORT" = T001L."LGORT"
	LEFT JOIN "LAKE"."TVSTT" ON 1=1
		AND VBAP."MANDT" = TVSTT."MANDT"
		AND VBAP."VSTEL" = TVSTT."VSTEL"
		AND TVSTT."SPRAS" = 'E'
		--AND TVSTT."SPRAS" = '{{SPRAS}}'
	LEFT JOIN "LAKE"."TVKMT" ON 1=1
		AND TVKMT."MANDT"=VBAP."MANDT"
		AND TVKMT."SPRAS" = 'E'
		--AND TVKMT."SPRAS" = '{{SPRAS}}'
		AND TVKMT."KTGRM"=VBAP."KTGRM"
	LEFT JOIN "LAKE"."TVAPT" ON 1=1
		AND VBAP."MANDT" = TVAPT."MANDT"
		AND VBAP."PSTYV" = TVAPT."PSTYV"
		AND TVAPT."SPRAS" = 'E'
		--AND TVAPT."SPRAS" = '{{SPRAS}}'
	LEFT JOIN "LAKE"."TVAGT" ON 1=1
	    AND VBAP."MANDT" = TVAGT."MANDT"
		AND VBAP."ABGRU" = TVAGT."ABGRU"
		AND TVAGT."SPRAS" = 'E'
		--AND TVAGT."SPRAS" = '{{SPRAS}}'
	LEFT JOIN "LAKE"."T023T" AS T023T on 1=1
	    AND T023T."MANDT" = VBAP."MANDT"
	    AND T023T."SPRAS" = 'E'
		--AND T023T."SPRAS" = '{{SPRAS}}'
	    AND T023T."MATKL" = VBAP."MATKL"
    /* NECESSARY FOR REHAU AUTH OBJ */
    -- LEFT JOIN "LAKE"."MARA" AS MARA ON 1=1
    --     AND MARA."MANDT" = VBAP."MANDT"
    --     AND MARA."MATNR" = VBAP."MATNR"
    /* END REHAU AUTH OBJ */
;