-- Query No: 1
CLEAR_INVOICE =
SELECT DISTINCT
	E."_CASE_KEY" AS "_CASE_KEY"
	,E."MANDT" AS "MANDT"
	,E."EBELN" AS "EBELN"
	,E."EBELP" AS "EBELP"
	,'AV: Gleiche Rechnung aus' AS "ACTIVITY_DE"
	,'AV: Clear Invoice' AS "ACTIVITY_EN"
	,CAST(CAST(BKPF_Z."CPUDT" AS DATE) || ' ' || CAST(BKPF_Z."CPUTM" AS TIME) AS TIMESTAMP) AS "EVENTTIME"
	,110 AS "_SORTING"
	--,BKPF_Z."USNAM" AS "USER_NAME"
	,USR02."USTYP" AS "USER_TYPE"
    ,NULL AS"CHANGED_TABLE"
    ,NULL AS"CHANGED_TABLE_TEXT_DE"
    ,NULL AS"CHANGED_TABLE_TEXT_EN"
    ,NULL AS"CHANGED_FIELD"
    ,NULL AS"CHANGED_FIELD_TEXT_DE"
    ,NULL AS"CHANGED_FIELD_TEXT_EN"
    ,NULL AS"CHANGED_FROM"
    ,NULL AS"CHANGED_TO" 
    ,NULL AS"CHANGED_FROM_FLOAT"
    ,NULL AS"CHANGED_TO_FLOAT"
    ,NULL AS"CHANGE_NUMBER"
	,BKPF_Z."TCODE" AS "TRANSACTION_CODE"
    ,NULL AS"_ORIGIN_SYS"
    ,NULL AS"LSLCODLSB"
    ,NULL AS"KOBCDOBNB"
    ,NULL AS"KOBERD"
    ,NULL AS"POBCOD"
FROM 
	"LAKE"."RSEG" AS RSEG
	JOIN :TMP_P2P_EKKO_EKPO AS E ON 1=1
	    AND RSEG."MANDT" = E."MANDT"
	    AND RSEG."EBELN" = E."EBELN"
	    AND RSEG."EBELP" = E."EBELP"
	JOIN :TMP_P2P_BKPF_BSEG AS B ON 1=1
		AND B."MANDT" = RSEG."MANDT"
		AND SUBSTRING(B."AWKEY", 1, 14) = RSEG."BELNR" || CAST(RSEG."GJAHR" AS VARCHAR(4))
	LEFT JOIN "LAKE"."BKPF" AS BKPF_Z ON 1=1
		AND B."MANDT" = BKPF_Z."MANDT"
		AND B."BUKRS" = BKPF_Z."BUKRS"
		AND B."AUGBL" = BKPF_Z."BELNR"
		AND YEAR(B."AUGDT") = BKPF_Z."GJAHR" -- HANA Dialect
		--AND CAST(EXTRACT(YEAR FROM B."AUGDT") AS INT) = CAST(BKPF_Z."GJAHR" AS INT) -- Postgres Dialect
	LEFT JOIN "LAKE"."USR02" AS USR02 ON 1=1
		AND BKPF_Z."MANDT" = USR02."MANDT"
		AND BKPF_Z."USNAM" = USR02."BNAME"
WHERE 1=1
    AND E."BSTYP" IN ('F')
	AND B."KOART" = 'K'	
	AND COALESCE(TRIM(B."AUGBL"), '') <> ''
	AND COALESCE(TRIM(BKPF_Z."CPUDT"), '') <> '' AND BKPF_Z."CPUDT" <> '00000000'
;